app1/urls.py
from app1.views import *
from django.urls import path
app_name='ramu'
urlpatterns=[
    path('ramu/',ramu,name='ramu'),
]

app2/urls.py
from app2.views import *
from django.urls import path
app_name='murali'
urlpatterns=[
    path('murali/',murali,name='murali'),
]

project4/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path("admin/", admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def ramu(request):
    return render(request,'ramu.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def murali(request):
    return render(request,'murali.html')

templates/murali.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>this is murali html page</h1>
        <a href="{% url 'ramu:ramu' %}">navigate to ramu</a>
    </center>
</body>
</html>

templates/ramu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>this is ramu html page</h1>
        <a href="{% url 'murali:murali' %}"> navigate to murali</a>
    </center>
</body>
</html>